baseURL = "https://tekito.org"
title = "tekito.org"
languageCode = "ja-jp"
theme = "hugo-coder"

googleAnalytics = "G-6EEEPYHCGB"

[pagination]
pagerSize = 20

[params]
author = "rim-buei"
info = ""
description = ""
keywords = "blog,developer"
avatarURL = "images/avatar.jpg"
since = 2010

colorScheme = "auto"
hideColorSchemeToggle = false

[[params.social]]
name = "GitHub"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/rim-buei"
[[params.social]]
name = "X"
icon = "fa-brands fa-x-twitter fa-2x"
weight = 2
url = "https://x.com/rim_buei"
[[params.social]]
name = "Steam"
icon = "fa-brands fa-steam fa-2x"
weight = 3
url = "https://steamcommunity.com/id/rim_buei"
[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-square-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/rim-buei"

[[menu.main]]
name = "Blog"
weight = 1
url = "posts/"
[[menu.main]]
name = "RSS Feed"
weight = 2
url = "index.xml"
